/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as MockInterviewRouteImport } from './routes/mock-interview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentRoadmapRouteImport } from './routes/student/roadmap'
import { Route as StudentResumeRouteImport } from './routes/student/resume'
import { Route as StudentResearchRouteImport } from './routes/student/research'
import { Route as StudentRegisterRouteImport } from './routes/student/register'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentOpportunitiesRouteImport } from './routes/student/opportunities'
import { Route as StudentMockInterviewRouteImport } from './routes/student/mock-interview'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as StudentInternshipsRouteImport } from './routes/student/internships'
import { Route as StudentHackathonsRouteImport } from './routes/student/hackathons'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentAssistantRouteImport } from './routes/student/assistant'
import { Route as StudentAssignmentsRouteImport } from './routes/student/assignments'
import { Route as RecruiterRegisterRouteImport } from './routes/recruiter/register'
import { Route as RecruiterLoginRouteImport } from './routes/recruiter/login'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter/jobs'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter/dashboard'
import { Route as RecruiterCandidatesRouteImport } from './routes/recruiter/candidates'
import { Route as RecruiterCandidateRouteImport } from './routes/recruiter/candidate'
import { Route as RecruiterAnalyticsRouteImport } from './routes/recruiter/analytics'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminRecruitersRouteImport } from './routes/admin/recruiters'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin/opportunities'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as ApiInterviewTtsRouteImport } from './routes/api/interview/tts'
import { Route as ApiInterviewSttRouteImport } from './routes/api/interview/stt'
import { Route as ApiInterviewChatRouteImport } from './routes/api/interview/chat'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MockInterviewRoute = MockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoadmapRoute = StudentRoadmapRouteImport.update({
  id: '/student/roadmap',
  path: '/student/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResumeRoute = StudentResumeRouteImport.update({
  id: '/student/resume',
  path: '/student/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResearchRoute = StudentResearchRouteImport.update({
  id: '/student/research',
  path: '/student/research',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/student/register',
  path: '/student/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentOpportunitiesRoute = StudentOpportunitiesRouteImport.update({
  id: '/student/opportunities',
  path: '/student/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMockInterviewRoute = StudentMockInterviewRouteImport.update({
  id: '/student/mock-interview',
  path: '/student/mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentInternshipsRoute = StudentInternshipsRouteImport.update({
  id: '/student/internships',
  path: '/student/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHackathonsRoute = StudentHackathonsRouteImport.update({
  id: '/student/hackathons',
  path: '/student/hackathons',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssistantRoute = StudentAssistantRouteImport.update({
  id: '/student/assistant',
  path: '/student/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/student/assignments',
  path: '/student/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRegisterRoute = RecruiterRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterLoginRoute = RecruiterLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCandidatesRoute = RecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCandidateRoute = RecruiterCandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterAnalyticsRoute = RecruiterAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RecruiterRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecruitersRoute = AdminRecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiInterviewTtsRoute = ApiInterviewTtsRouteImport.update({
  id: '/api/interview/tts',
  path: '/api/interview/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewSttRoute = ApiInterviewSttRouteImport.update({
  id: '/api/interview/stt',
  path: '/api/interview/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewChatRoute = ApiInterviewChatRouteImport.update({
  id: '/api/interview/chat',
  path: '/api/interview/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRoute
  '/candidate': typeof CandidateRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/opportunities': typeof OpportunitiesRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/sessions': typeof SessionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidate': typeof RecruiterCandidateRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/login': typeof RecruiterLoginRoute
  '/recruiter/register': typeof RecruiterRegisterRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/hackathons': typeof StudentHackathonsRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/mock-interview': typeof StudentMockInterviewRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/research': typeof StudentResearchRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/api/interview/chat': typeof ApiInterviewChatRoute
  '/api/interview/stt': typeof ApiInterviewSttRoute
  '/api/interview/tts': typeof ApiInterviewTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRoute
  '/candidate': typeof CandidateRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/opportunities': typeof OpportunitiesRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/sessions': typeof SessionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidate': typeof RecruiterCandidateRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/login': typeof RecruiterLoginRoute
  '/recruiter/register': typeof RecruiterRegisterRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/hackathons': typeof StudentHackathonsRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/mock-interview': typeof StudentMockInterviewRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/research': typeof StudentResearchRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/api/interview/chat': typeof ApiInterviewChatRoute
  '/api/interview/stt': typeof ApiInterviewSttRoute
  '/api/interview/tts': typeof ApiInterviewTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRoute
  '/candidate': typeof CandidateRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mock-interview': typeof MockInterviewRoute
  '/opportunities': typeof OpportunitiesRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/register': typeof RegisterRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/sessions': typeof SessionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidate': typeof RecruiterCandidateRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/dashboard': typeof RecruiterDashboardRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/login': typeof RecruiterLoginRoute
  '/recruiter/register': typeof RecruiterRegisterRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/assistant': typeof StudentAssistantRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/hackathons': typeof StudentHackathonsRoute
  '/student/internships': typeof StudentInternshipsRoute
  '/student/login': typeof StudentLoginRoute
  '/student/mock-interview': typeof StudentMockInterviewRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/research': typeof StudentResearchRoute
  '/student/resume': typeof StudentResumeRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/api/interview/chat': typeof ApiInterviewChatRoute
  '/api/interview/stt': typeof ApiInterviewSttRoute
  '/api/interview/tts': typeof ApiInterviewTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/assignments'
    | '/candidate'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mock-interview'
    | '/opportunities'
    | '/recruiter'
    | '/register'
    | '/resume'
    | '/roadmap'
    | '/sessions'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/opportunities'
    | '/admin/recruiters'
    | '/admin/sessions'
    | '/admin/students'
    | '/recruiter/analytics'
    | '/recruiter/candidate'
    | '/recruiter/candidates'
    | '/recruiter/dashboard'
    | '/recruiter/jobs'
    | '/recruiter/login'
    | '/recruiter/register'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/dashboard'
    | '/student/hackathons'
    | '/student/internships'
    | '/student/login'
    | '/student/mock-interview'
    | '/student/opportunities'
    | '/student/profile'
    | '/student/register'
    | '/student/research'
    | '/student/resume'
    | '/student/roadmap'
    | '/api/interview/chat'
    | '/api/interview/stt'
    | '/api/interview/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/assignments'
    | '/candidate'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mock-interview'
    | '/opportunities'
    | '/recruiter'
    | '/register'
    | '/resume'
    | '/roadmap'
    | '/sessions'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/opportunities'
    | '/admin/recruiters'
    | '/admin/sessions'
    | '/admin/students'
    | '/recruiter/analytics'
    | '/recruiter/candidate'
    | '/recruiter/candidates'
    | '/recruiter/dashboard'
    | '/recruiter/jobs'
    | '/recruiter/login'
    | '/recruiter/register'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/dashboard'
    | '/student/hackathons'
    | '/student/internships'
    | '/student/login'
    | '/student/mock-interview'
    | '/student/opportunities'
    | '/student/profile'
    | '/student/register'
    | '/student/research'
    | '/student/resume'
    | '/student/roadmap'
    | '/api/interview/chat'
    | '/api/interview/stt'
    | '/api/interview/tts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/assignments'
    | '/candidate'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mock-interview'
    | '/opportunities'
    | '/recruiter'
    | '/register'
    | '/resume'
    | '/roadmap'
    | '/sessions'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/opportunities'
    | '/admin/recruiters'
    | '/admin/sessions'
    | '/admin/students'
    | '/recruiter/analytics'
    | '/recruiter/candidate'
    | '/recruiter/candidates'
    | '/recruiter/dashboard'
    | '/recruiter/jobs'
    | '/recruiter/login'
    | '/recruiter/register'
    | '/student/assignments'
    | '/student/assistant'
    | '/student/dashboard'
    | '/student/hackathons'
    | '/student/internships'
    | '/student/login'
    | '/student/mock-interview'
    | '/student/opportunities'
    | '/student/profile'
    | '/student/register'
    | '/student/research'
    | '/student/resume'
    | '/student/roadmap'
    | '/api/interview/chat'
    | '/api/interview/stt'
    | '/api/interview/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CandidateRoute: typeof CandidateRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MockInterviewRoute: typeof MockInterviewRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  RecruiterRoute: typeof RecruiterRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResumeRoute: typeof ResumeRoute
  RoadmapRoute: typeof RoadmapRoute
  SessionsRoute: typeof SessionsRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAssistantRoute: typeof StudentAssistantRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentHackathonsRoute: typeof StudentHackathonsRoute
  StudentInternshipsRoute: typeof StudentInternshipsRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentMockInterviewRoute: typeof StudentMockInterviewRoute
  StudentOpportunitiesRoute: typeof StudentOpportunitiesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
  StudentResearchRoute: typeof StudentResearchRoute
  StudentResumeRoute: typeof StudentResumeRoute
  StudentRoadmapRoute: typeof StudentRoadmapRoute
  ApiInterviewChatRoute: typeof ApiInterviewChatRoute
  ApiInterviewSttRoute: typeof ApiInterviewSttRoute
  ApiInterviewTtsRoute: typeof ApiInterviewTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview': {
      id: '/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof MockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/roadmap': {
      id: '/student/roadmap'
      path: '/student/roadmap'
      fullPath: '/student/roadmap'
      preLoaderRoute: typeof StudentRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/resume': {
      id: '/student/resume'
      path: '/student/resume'
      fullPath: '/student/resume'
      preLoaderRoute: typeof StudentResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/research': {
      id: '/student/research'
      path: '/student/research'
      fullPath: '/student/research'
      preLoaderRoute: typeof StudentResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/register': {
      id: '/student/register'
      path: '/student/register'
      fullPath: '/student/register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/opportunities': {
      id: '/student/opportunities'
      path: '/student/opportunities'
      fullPath: '/student/opportunities'
      preLoaderRoute: typeof StudentOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/mock-interview': {
      id: '/student/mock-interview'
      path: '/student/mock-interview'
      fullPath: '/student/mock-interview'
      preLoaderRoute: typeof StudentMockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/internships': {
      id: '/student/internships'
      path: '/student/internships'
      fullPath: '/student/internships'
      preLoaderRoute: typeof StudentInternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/hackathons': {
      id: '/student/hackathons'
      path: '/student/hackathons'
      fullPath: '/student/hackathons'
      preLoaderRoute: typeof StudentHackathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assistant': {
      id: '/student/assistant'
      path: '/student/assistant'
      fullPath: '/student/assistant'
      preLoaderRoute: typeof StudentAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/student/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/register': {
      id: '/recruiter/register'
      path: '/register'
      fullPath: '/recruiter/register'
      preLoaderRoute: typeof RecruiterRegisterRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/login': {
      id: '/recruiter/login'
      path: '/login'
      fullPath: '/recruiter/login'
      preLoaderRoute: typeof RecruiterLoginRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/jobs': {
      id: '/recruiter/jobs'
      path: '/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/dashboard': {
      id: '/recruiter/dashboard'
      path: '/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/candidates': {
      id: '/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof RecruiterCandidatesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/candidate': {
      id: '/recruiter/candidate'
      path: '/candidate'
      fullPath: '/recruiter/candidate'
      preLoaderRoute: typeof RecruiterCandidateRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/analytics': {
      id: '/recruiter/analytics'
      path: '/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof RecruiterAnalyticsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recruiters': {
      id: '/admin/recruiters'
      path: '/recruiters'
      fullPath: '/admin/recruiters'
      preLoaderRoute: typeof AdminRecruitersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/interview/tts': {
      id: '/api/interview/tts'
      path: '/api/interview/tts'
      fullPath: '/api/interview/tts'
      preLoaderRoute: typeof ApiInterviewTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview/stt': {
      id: '/api/interview/stt'
      path: '/api/interview/stt'
      fullPath: '/api/interview/stt'
      preLoaderRoute: typeof ApiInterviewSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview/chat': {
      id: '/api/interview/chat'
      path: '/api/interview/chat'
      fullPath: '/api/interview/chat'
      preLoaderRoute: typeof ApiInterviewChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRoute
  AdminRecruitersRoute: typeof AdminRecruitersRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRoute,
  AdminRecruitersRoute: AdminRecruitersRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RecruiterRouteChildren {
  RecruiterAnalyticsRoute: typeof RecruiterAnalyticsRoute
  RecruiterCandidateRoute: typeof RecruiterCandidateRoute
  RecruiterCandidatesRoute: typeof RecruiterCandidatesRoute
  RecruiterDashboardRoute: typeof RecruiterDashboardRoute
  RecruiterJobsRoute: typeof RecruiterJobsRoute
  RecruiterLoginRoute: typeof RecruiterLoginRoute
  RecruiterRegisterRoute: typeof RecruiterRegisterRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterAnalyticsRoute: RecruiterAnalyticsRoute,
  RecruiterCandidateRoute: RecruiterCandidateRoute,
  RecruiterCandidatesRoute: RecruiterCandidatesRoute,
  RecruiterDashboardRoute: RecruiterDashboardRoute,
  RecruiterJobsRoute: RecruiterJobsRoute,
  RecruiterLoginRoute: RecruiterLoginRoute,
  RecruiterRegisterRoute: RecruiterRegisterRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AssignmentsRoute: AssignmentsRoute,
  CandidateRoute: CandidateRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MockInterviewRoute: MockInterviewRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  RecruiterRoute: RecruiterRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResumeRoute: ResumeRoute,
  RoadmapRoute: RoadmapRoute,
  SessionsRoute: SessionsRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAssistantRoute: StudentAssistantRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentHackathonsRoute: StudentHackathonsRoute,
  StudentInternshipsRoute: StudentInternshipsRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentMockInterviewRoute: StudentMockInterviewRoute,
  StudentOpportunitiesRoute: StudentOpportunitiesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRegisterRoute: StudentRegisterRoute,
  StudentResearchRoute: StudentResearchRoute,
  StudentResumeRoute: StudentResumeRoute,
  StudentRoadmapRoute: StudentRoadmapRoute,
  ApiInterviewChatRoute: ApiInterviewChatRoute,
  ApiInterviewSttRoute: ApiInterviewSttRoute,
  ApiInterviewTtsRoute: ApiInterviewTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
